server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
<<<<<<< HEAD
  
  # Distributed Tracing Configuration
  zipkin:
    base-url: http://localhost:9411

# Additional Tracing Configuration
zipkin:
  base-url: http://localhost:9411

# Logging Configuration for Trace IDs
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
=======
>>>>>>> 18b3f5cbe4e2b027e2f5f420a9624f9ff2fb6d3d
