server:
  port: 8888

spring:
  application:
    name: config-server
  
  # Distributed Tracing Configuration
  zipkin:
    base-url: http://localhost:9411
  
  cloud:
    config:
      server:
        git:
          uri: file:///${user.dir}/../config-repo
          default-label: master
          clone-on-start: true

# Additional Tracing Configuration
zipkin:
  base-url: http://localhost:9411

# Logging Configuration for Trace IDs
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
